micronaut:
  application:
    name: lombokRepro
netty:
  default:
    allocator:
      max-order: 3
flyway:
  enabled: true
  datasources:
    default:
      enabled: true
      locations:
        - classpath:migration
datasources:
  default:
    host: localhost:5432
    database-name: lombok_repro
    url: jdbc:postgresql://${datasources.default.host}/${datasources.default.database-name}
    username: postgres
    password: postgres
    maximum-pool-size: 10
    minimum-idle: 1
    schema-generate: NONE